version: "3.5"

services:
  app:
    build: .
    image: softlab-exam
    container_name: softlab-exam
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: 'dbc:postgresql://localhost:5432/softlabexam'
  postgres:
    image: postgres:14-alpine
    container_name: postgres-docker-softlab-exam
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: